### ISSUE TITLE
background + workshop code review

### ISSUE THREAD

**Issue by naomitress** [ocean-tracking-network/2022-05-FACT-workshop#19]
pls run and pr any errors found in https://github.com/ocean-tracking-network/2022-05-FACT-workshop/tree/gh-pages/code/day1 (note branch)

**Comment by CaitlinBate** [comment]
fyi Jon - code is in gh-pages, but the datasets we wanna use are in master it looks like

**Comment by naomitress** [comment]
> fyi Jon - code is in gh-pages, but the datasets we wanna use are in master it looks like

code and data in master now
