### ISSUE TITLE
remove non-FACT datasets

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2022-05-FACT-workshop#2]
- cut out other data sets from master and gh-pages data folder
- ensure lessons are also FACT-only

**Comment by naomitress** [comment]
potentially complete once https://github.com/ocean-tracking-network/2022-05-FACT-workshop/pull/14 is done

**Comment by naomitress** [comment]
not yet done in master

**Comment by naomitress** [comment]
code cleaned out of gh-pages and master
