### ISSUE TITLE
website setup

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2022-05-FACT-workshop#3]
- [ ] change status to beta (after closing https://github.com/ocean-tracking-network/2022-05-FACT-workshop/pull/22)
- edit index.md
- edit config.yml
- edit readme on both master and gh-pages

**Comment by naomitress** [comment]
doing in [nt_websetup](https://github.com/ocean-tracking-network/2022-05-FACT-workshop/tree/nt_websetup)

**Comment by naomitress** [comment]
merged
